### ISSUE TITLE
Lose Lena?

### ISSUE THREAD

**Issue by cormullion** [JuliaImages/TestImages.jl#72] opened 2020-07-18 19:59 UTC
https://womenlovetech.com/losing-lena-why-we-need-to-remove-one-image-and-end-techs-original-sin/

**Comment by johnnychen94** [comment] 2020-07-19 06:55
Hmmm, any suggestions on how to proceed with this? Simply removing it might be troublesome.

**Comment by cormullion** [comment] 2020-07-19 14:10
“Deprecate” applies in all senses here... 🤓  Does Julia’s deprecation tools it work here!

**Comment by johnnychen94** [comment] 2020-07-20 02:09
Given that `lena*` is still one of the standard test images, removing it from the dataset can be problematic. The best strategy to me is a permanent deprecation.

However, since Julia 1.5  `@deprecate` doesn't get triggered unless users start julia with `--depwarn=yes`... And normal users don't really enable this. We might need to find a way to mimic how `@deprecate` works prior to Julia 1.5; a must-to-print deprecation.

**Comment by zygmuntszpak** [comment] 2020-07-20 05:17
I'm not convinced that the best solution involves removing Lena from `TestImages.jl`. There is a case to be made for _reproducible research_. Countless published papers report specific results on this particular image, and it is extremely helpful to validate an implementation by comparing with published results. 

One can refrain from using the Lena image in future publications even if the image is still accessible in TestImages. We could also potentially decide not to use it in the JuliaImages Documentation ecosystem.

**Comment by cormullion** [comment] 2020-07-20 05:26
Why not rename a copy of this package to LegacyTestImages, and then move TestImages forward with a new Lena-less release. People can then choose as required.

**Comment by johnnychen94** [comment] 2020-07-20 05:34
My whole concern is: we could recommend researchers to not use Lena, but we couldn't force them to not use it.; people will try to get `lena` from other resources if that's unavailable in TestImages and that's not convenient...

**Comment by timholy** [comment] 2020-07-20 16:45
See ancient discussion starting in https://github.com/JuliaImages/TestImages.jl/pull/19#issuecomment-207551029. I'm happy to discuss this further, but let's all read that first and then continue.

**Comment by timholy** [comment] 2020-07-21 18:59
I hadn't clicked on the link, so I didn't realize that she herself has asked to have the image removed (not just "not used," but removed). Seems like a no-brainer, then? It's a picture of her, having control over that seems only fair.

But assuming we do this, we should deprecate the image for a period before removing it.

More discussion is welcome, of course.

**Comment by cormullion** [comment] 2020-07-21 19:09
go for it. We're catching up with [scipy](https://github.com/scipy/scipy/pull/5162)... 😂

**Comment by timholy** [comment] 2020-07-21 21:24
None of those other frameworks added a counterbalancing image, though.

**Comment by cormullion** [comment] 2020-07-21 21:36
True. I'd still recommend removing these images first, before bike-shedding some replacements. Fortunately we're living in an age where we're spoilt for choice.

**Comment by timholy** [comment] 2020-07-21 22:31
I generally feel we need to have a deprecation period---removing test data is a breaking change, and it's not nice to do that without a little bit of warning.

It can even be educational, if someone says `testimage("lena")` then we can temporarily still return the image but also print a warning that the image is going away and even include a link explaining the issues. This is basically how all deprecations in Julia work.

**Comment by johnnychen94** [comment] 2020-07-21 22:49
Given that deprecation is now invisible unless users start Julia with `--depwarn=yes`, I prefer to make it a permanent warning. Make it permanent because there is still such a need for benchmark usage. For demo usage, we can immediately replace that with others.

Barbara in #79 is also used widely for benchmark and demo, will that be an issue if we include it?

**Comment by timholy** [comment] 2020-07-22 18:15
I don't see it as political; this is a case where the subject of the picture has asked that it to be removed. Unless the subject in the Barbara image has made a similar request, I don't think there's anything we need to do.

I would do the same thing if we had written some code based on published software that was not clear about its license, and later the author retrospectively clarified that it was not intended as a BSD/MIT-compatible release and asked us to remove the implementation.

**Comment by johnnychen94** [comment] 2020-07-22 23:29
I probably misunderstood the whole issue here. I'm on the board if this is all about the license, regardless of whatever the original purpose of such a request is.

We could add an explicit warning (not depwarn) in next TestImages release, and remove it in `v2.0.0`

**Comment by zygmuntszpak** [comment] 2020-07-23 04:28
> I don't see it as political; this is a case where the subject of the picture has asked that it to be removed. Unless the subject in the Barbara image has made a similar request, I don't think there's anything we need to do.

It might be worth clarifying the policy a bit further. In the instance of Lena the subject is not the copyright holder. Are we saying that a picture will be removed when either the copyright holder of the image, or a subject in the image (who may not be the copyright holder) asks for it to be removed? 

It  is regrettable that Lena Forsén (nee Söderberg) was not more precise in her wishes. In  [the documentary](https://www.facebook.com/codelikeagirlau/videos/985614161797010/) she speaks on the issue at 23:28 and says

> I was proud about that picture, I thought it was pretty nice. At the time I don't think we thought about that it was wrong. I think it was, well this is the way it is.  I really think its different today than it was back in the 70s. It's a man's world, or it was. I think we're coming a long way but there's a lot of work to do and everybody has to take their part. Once upon a time I was the centerfold of Playboy but I retired from modelling a long time ago. It's time I retire from tech too.

I interpret "it's time I retire from tech too" as "let us not continue to use me as a model for testing the efficacy of new image processing algorithms". I don't associate "retirement" with "let us expunge any traces of my image from the internet". The pledge on the ["Losing Lena"](https://www.losinglena.com/) website asks people to commit to not using Lena, not to commit to removing it from archives.  

The article that Cormullion linked to states:

> Now, Lena is joined by multiple organisations including Code Like A Girl in her plea to the world to have the image of herself be removed.

So it definitely seems that some people are interpreting her comments about retirement as "a plea to the world to have the image of herself be removed".

I echo Johnny's initial concerns which were:

> My whole concern is: we could recommend researchers to not use Lena, but we couldn't force them to not use it.; people will try to get lena from other resources if that's unavailable in TestImages, which is not convenient...

 There is still the counterbalancing issue of facilitating reproducible research. Decades worth of published research in image processing is based on this image. 

> I would do the same thing if we had written some code based on published software that was not clear about its license, and later the author retrospectively clarified that it was not intended as a BSD/MIT-compatible release and asked us to remove the implementation.

I appreciate the analogy, but I think the time dimension matters too. If I was using your code, invited you to a conference as a [guest of honour](http://www.lenna.org/lenna_visit.html) where I showcased all the amazing work I was able to do with your code and what I intend to do with it, and then 30 years later you objected about it, I would probably find it hard to accommodate you. Of course everyone is entitled to change their mind but whole issue would probably not be a "no brainer".  

In any case, this is not a hill I want to die on. I haven't had a need for the Lena image in any of my own work so far and probably won't in the future. I just wanted to leave a record of a different perspective, in the spirit of "diversity of thought".

**Comment by timholy** [comment] 2020-07-23 21:07
Very good post @zygmuntszpak. No matter what the final outcome here, a respectful and well-reasoned counterargument is always welcome.

Given that JuliaCon is about to ramp up and I'm pretty swamped with many things, I don't plan on taking action until after the conference anyway, so this can continue to accumulate viewpoints.

**Comment by johnnychen94** [comment] 2020-10-03 01:31
A deprecation warning is added in #84 and will be released in the next release.

My preference for this deprecation is to make it permanent; my only argument about this is: the need for lena in reproducible experiments can't be suppressed even if we delete that from TestImages.

I'm closing this now, but if there are further concerns, feel free to reopen it.

**Closed by johnnychen94** 2020-10-03 01:31 UTC
